name: Build

on:
  workflow_dispatch:

jobs:
  maven_build:
    name: Maven Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verify Java version
        run: java -version

      - name: Add Maven to PATH
        run: echo "/opt/maven/bin" >> $GITHUB_PATH

      - name: Verify Maven installation
        run: mvn -version

      - name: Maven Clean Package
        run: mvn clean package

      - name: Publish WAR to Artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
               -T target/*.war \
               "$ARTIFACTORY_URL/com.nagarro.dpcode/binaries/$(basename target/*.war)"

      - name: Upload WAR file to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: war-file
          path: target/*.war

  docker_build_and_push:
    name: Docker Build and Push
    runs-on: self-hosted
    needs: maven_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download WAR file
        uses: actions/download-artifact@v2
        with:
          name: war-file
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker installation
        run: docker --version

      - name: Build Docker image
        run: docker build --build-arg ARTIFACTORY_USERNAME=${{ secrets.ARTIFACTORY_USERNAME }} --build-arg ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }} -t ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }}
