name: Build and Push Docker Image
on:
  workflow_dispatch:

jobs:
  build:
    name: Maven Build
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Add Maven to PATH
        run: echo "/opt/maven/bin" >> $GITHUB_PATH
          
      - name: Maven Clean Package
        run: mvn clean package
        
      - name: Upload WAR file
        uses: actions/upload-artifact@v2
        with:
          name: war-file
          path: target/*.war

  docker_build_and_push:
    name: Docker Build and Push
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download WAR file
        uses: actions/download-artifact@v2
        with:
          name: war-file
          path: target

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }} .
        
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }}
