name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout_code:
    name: Checkout Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  maven_package:
    name: Maven Clean Package
    runs-on: ubuntu-latest
    needs: checkout_code
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Maven Clean Package
        run: mvn clean package
        
      - name: Upload WAR file
        uses: actions/upload-artifact@v2
        with:
          name: war-file
          path: target/CalculatorMvcProject.war

  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: maven_package
    
    steps:
      - name: Download WAR file
        uses: actions/download-artifact@v2
        with:
          name: war-file
          path: target

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/java:${{ github.run_number }} -f Dockerfile .

  docker_push:
    name: Docker Push
    runs-on: ubuntu-latest
    needs: docker_build
    
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java:${{ github.run_number }}
