name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    name: Maven Build and Docker Push
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Add Maven to PATH
        run: echo "/opt/maven/bin" >> $GITHUB_PATH

      - name: Maven Clean Package
        run: mvn clean package

      - name: Publish WAR to Artifactory
        stage: Publish to Artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
               -T target/*.war \
               "$ARTIFACTORY_URL/com.nagarro.dpcode/binaries/$(basename target/*.war)"

      - name: Upload WAR file to GitHub
        stage: Upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: war-file
          path: target/*.war

      - name: Build Docker image
        stage: Build Docker Image
        run: docker build --build-arg ARTIFACTORY_USERNAME=${{ secrets.ARTIFACTORY_USERNAME }} --build-arg ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }} -t ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }} .

      - name: Push Docker image
        stage: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }}
