name: dpcode

on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout
    runs-on: dpcode
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  maven_build:
    name: Maven Build
    runs-on: dpcode
    needs: checkout
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Add Maven to PATH
        run: echo "/opt/apache-maven-3.9.7/bin" >> $GITHUB_PATH

      - name: Maven Clean Package
        run: mvn clean package

  unit_test:
    name: Unit Test and Code Coverage
    runs-on: dpcode
    needs: maven_build
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Add Maven to PATH
        run: echo "/opt/apache-maven-3.9.7/bin" >> $GITHUB_PATH

      - name: Run Unit Tests
        run: mvn test

      - name: Generate JaCoCo Code Coverage Report
        run: mvn jacoco:report

      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/surefire-reports

      - name: Archive JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco

  sonarqube_analysis:
    name: SonarQube Analysis
    runs-on: dpcode-1
    needs: unit_test
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Add Maven to PATH
        run: echo "/opt/apache-maven-3.9.7/bin" >> $GITHUB_PATH

      - name: SonarQube Scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=CalculatorMvcProject -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  upload_to_artifactory:
    name: Upload to Artifactory
    runs-on: dpcode
    needs: sonarqube_analysis
    steps:
      - name: Publish WAR to Artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD \
               -T target/*.war \
               "$ARTIFACTORY_URL/com.DevOps.pipeline/binaries/$(basename target/*.war)"

  docker_build:
    name: Docker Image Build
    runs-on: dpcode
    needs: upload_to_artifactory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build --build-arg ARTIFACTORY_USERNAME=${{ secrets.ARTIFACTORY_USERNAME }} \
                       --build-arg ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }} .

  docker_push:
    name: Docker Image Push
    runs-on: dpcode
    needs: docker_build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/java-app:${{ github.run_number }}
